# Generated by Django 4.2 on 2023-04-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_userprofile_todo_entity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_entity',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
